version: '3.8'
services:
  mqtt_dtblock:
    image: eclipse-mosquitto:2.0
    container_name: Integrador_MQTT
    restart: unless-stopped
    ports:
      - "${HOST_ADDRESS}:${HOST_PORT}:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

volumes:
  mosquitto-data:
  mosquitto-log: