# config/mosquitto.conf

# -----------------------------------------------------------------
# Core Settings
# -----------------------------------------------------------------
# Disable persistence since the system relies on real-time data
persistence true
persistence_location /mosquitto/data/

# -----------------------------------------------------------------
# Listeners & Security
# -----------------------------------------------------------------
# Listen on the default MQTT port
listener 1883

# Enable anonymous access
allow_anonymous true

# -----------------------------------------------------------------
# Logging & Traceability
# -----------------------------------------------------------------
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S
log_type all