# Standard library imports
import sys
import os
import pickle   # Serialization
import base64   # Parsing to string

# Related third party imports
import omni.kit.app
import carb.events
import numpy as np
import matplotlib.pyplot as plt
from omni.kit.scripting import BehaviorScript
from pxr import Sdf, Gf
from scipy.spatial.transform import Rotation
import omni.physx
import omni.timeline
from omni.isaac.core.prims import RigidPrimView
# DEBUG
import logging


project_root_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../..'))
# Add root 'project' folder to sys.path
if project_root_path not in sys.path:
    sys.path.append(project_root_path)


# Local application/library specific imports
from uspace.flight_plan.flight_plan import FlightPlan
from uspace.flight_plan.waypoint import Waypoint
from uspace.flight_plan.command import Command


class UAM_minidrone(BehaviorScript):

    def on_init(self):
        # DEBUG
        self.logger = logging.getLogger("A_my_logger")
        self.logger.info(f"INIT  {self.prim_path}")

        self.timeline_sub = self.timeline.get_timeline_event_stream().create_subscription_to_pop_by_type(
            int(omni.timeline.TimelineEventType.STOP), self.reset_current_time)

        self.physx_interface = omni.physx.get_physx_interface()
        self.physics_sub = self.physx_interface.subscribe_physics_step_events(self.on_physics_step)

        self.current_time = 0
        self.delta_time = 0

        prim_paths = ["/abejorro/chasis", "/abejorro/rotor_NE", "/abejorro/rotor_NW", "/abejorro/rotor_SE",
                      "/abejorro/rotor_SW"]
        prim_masses = [0.555, 0.01, 0.01, 0.01, 0.01]
        self.rigid_prim_view = RigidPrimView(prim_paths_expr=prim_paths, masses=prim_masses)
        self.rigid_prim_view_initialized = False

        # Create the omniverse event associated to this UAV
        self.UAV_EVENT = carb.events.type_from_string("NavSim." + str(self.prim.GetPath()))
        bus = omni.kit.app.get_app().get_message_bus_event_stream()
        self.uav_event_sub = bus.create_subscription_to_push_by_type(self.UAV_EVENT, self.push_subscripted_event_method)

        #--------------------------------------------------------------------------------------------------------------
        # NAVIGATION PARAMETERS

        self.fp = None               
        self.currentWP = None  

        # AutoPilot navigation command
        self.command = Command()
        self.cmd_exp_time = 0

        # Tracking
        self.tracking_figure_builded = False
        self.refresh_rate = 1
        self.last_time_track = 0
        self.track_info = []

        #--------------------------------------------------------------------------------------------------------------
        # QUADCOPTER PARAMETERS

        self.g    = 9.81

        self.mass = 0.595
        # print(f"mass: {self.mass}")
        
        self.pos_atr    = self.prim.GetChild("chasis").GetAttribute("xformOp:translate")
        self.ori_atr    = self.prim.GetChild("chasis").GetAttribute("xformOp:orient")

        self.linVel_atr = self.prim.GetChild("chasis").GetAttribute("physics:velocity")
        self.angVel_atr = self.prim.GetChild("chasis").GetAttribute("physics:angularVelocity")

        inertia_attr = self.prim.GetChild("chasis").GetAttribute("physics:diagonalInertia")
        self.inertia = inertia_attr.Get()
        # print(f"inertia: {self.inertia}")

        self.pos   = Gf.Vec3f(0, 0, 0)
        self.roll  = 0
        self.pitch = 0
        self.yaw   = 0
        self.linear_vel  = Gf.Vec3f(0, 0, 0)
        self.angular_vel = Gf.Vec3f(0, 0, 0)

        # Rotor speed (rad/s)
        # asumimos velocidad máxima de 6000rpm = 628.3185 rad/s
        self.w_rotor_NE = 0.0
        self.w_rotor_NW = 0.0
        self.w_rotor_SE = 0.0
        self.w_rotor_SW = 0.0
    
        # Max and minimum angular velocity of the motors
        self.w_max = 628.3185      # rad/s = 15000rpm
        self.w_min = 0             # rad/s =     0rpm

        # Aerodynamic thrust force constant
        # Force generated by the rotors is FT = kFT * w²
        self.kFT = 1.7197e-05                                    # assuming that FT_max = 0.692kg
        self.w_hov = (self.mass * self.g / 4 / self.kFT) ** 0.5  # 291.45 rad/s

        # Aerodynamic drag force constant
        # Moment generated by the rotors is MDR = kMDR * w²
        self.kMDR = 3.6714e-08

        # Aerodynamic drag force constant per axis
        # Drag force generated by the air friction, opposite to the velocity is FD = -kFD * r_dot*|r_dot| (depends on 
        # the shape of the object in each axis).
        # Horizontal axis:
        self.kFDx = 1.1902e-04
        self.kFDy = 1.1902e-04
        # Vertical axis:
        self.kFDz = 36.4437e-4

        # Aerodynamic drag moment constant per axis
        # Drag moment generated by the air friction, opposite to the angular velocity is MD = -kMD * rpy_dot*|rpy_dot| 
        # (depends on the shape of the object in each axis).

        # Horizontal axis:
        # Assuming similar drag in both axes (although the fuselage is not equal), no gravity and the drone is 
        # propulsed by two rotors of the same side at maximum speed the maximum angular velocity is Vrp_max = 2 * 2*pi;
        # operating kMDxy =  2 * FT_max * sin(deg2rad(45))^2 / Vrp_max^2 we get that...
        self.kMDx = 1.1078e-04
        self.kMDy = 1.1078e-04

        # Vertical axis:
        # Must be verified at maximum yaw velocity
        # Assuming that Vyaw_max = 4*pi rad/s (max yaw velocity of 2rev/s) and w_hov2 (rotor speed to maintain the 
        # hovering) And taking into account that MDR = kMDR * w² and MDz = kMDz * Vyaw² operating MDz  = MDR (the air 
        # friction compensates the effect of the rotors) and kMDz = kMDR* (2 * w_hov2²) / Vyaw_max² we get that...
        self.kMDz = 7.8914e-05

        #--------------------------------------------------------------------------------------------------------------
        # LOW LEVEL CONTROL

        self.x  = np.zeros((8, 1))  # model state
        self.y  = np.zeros((4, 1))  # model output
        self.u  = np.zeros((4, 1))  # input (rotors speeds)
        self.r  = np.zeros((4, 1))  # model reference
        self.e  = np.zeros((4, 1))  # model error
        self.E  = np.zeros((4, 1))  # model accumulated error
        
        self.Kx = np.array([        # state control matrix
            [-47.4820, -47.4820, -9.3626, -9.3626,  413.1508, -10.5091,  10.5091,  132.4440],
            [ 47.4820, -47.4820,  9.3626, -9.3626, -413.1508, -10.5091, -10.5091,  132.4440],
            [-47.4820,  47.4820, -9.3626,  9.3626, -413.1508,  10.5091,  10.5091,  132.4440],
            [ 47.4820,  47.4820,  9.3626,  9.3626,  413.1508,  10.5091, -10.5091,  132.4440]
        ])


        self.Ky = np.array([        # error control matrix
            [-8.1889,  8.1889,  294.3201,  918.1130],
            [-8.1889, -8.1889,  294.3201, -918.1130],
            [ 8.1889,  8.1889,  294.3201, -918.1130],
            [ 8.1889, -8.1889,  294.3201,  918.1130]
        ])

        self.Hs = np.array([        # hovering speed
            [self.w_hov], 
            [self.w_hov], 
            [self.w_hov], 
            [self.w_hov]
        ])
        
        self.E_max = 15  # previous value 5, maximum model accumulated error

    def on_destroy(self):
        self.timeline_sub = None
        self.physics_sub = None
        self.uav_event_sub = None
    #------------------------------------------------------------------------------------------------------------------
    # EVENT HANDLERS

    def on_play(self):
        # Tracking
        self.show_tracking = False
        self.refresh_rate = 1
        self.last_time_track = 0

        # Update the drone status
        self.imu()
        self.navigation()
        self.command.hover()
        self.servo_control()
        self.platform_dynamics()
        # self.telemetry()

    def on_pause(self):
        # print(f"PAUSE   {self.prim_path}")
        pass

    def on_physics_step(self, step_size):
        self.current_time += step_size
        self.delta_time = step_size

        if not self.rigid_prim_view_initialized:
            self.rigid_prim_view.initialize()
            self.rigid_prim_view_initialized = True

        self.update()

    def reset_current_time(self, event):
        self.current_time = 0

    def on_stop(self):
        self.rigid_prim_view_initialized = False
        self.current_time = 0
        self.delta_time = 0

        self.command.off()
        self.rotors_off()
    
        self.fp = None

        self.tracking_figure_builded = False
        self.track_info = []

    def update(self):

        # Update the drone status
        self.imu()
        self.navigation()
        self.servo_control()
        self.platform_dynamics()
        # self.telemetry()

    def push_subscripted_event_method(self, e):       

        try:
            method = getattr(self, e.payload["method"]) 
        except:
            print(f"Method {e.payload['method']} not found")
            return
        
        match e.payload["method"]:
            case "eventFn_RemoteCommand":
                method(e.payload["command"])
            case "eventFn_FlightPlan":
                method(e.payload["fp"])
            case _:
                method()
            
    def eventFn_RemoteCommand(self, command):
        self.command : Command = pickle.loads(base64.b64decode(command))
        if self.command.duration is not None:
            self.cmd_exp_time = self.current_time + self.command.duration
            print(f"[{self.current_time}] {self.prim_path}: command received")

            # Adapt command to horizont axes
            # vel_x = np.cos(self.pitch) * self.command.velX
            # vel_y = np.cos(self.roll) * self.command.velY
            # vel_z = np.sin(self.pitch) + np.sin(self.roll) + self.command.velZ
            
            # self.command.set(self.command.on, vel_x, vel_y, vel_z, self.command.rotZ, self.command.duration)
            # self.command.velX = vel_x
            # self.command.velY = vel_y
            # self.command.velZ = vel_z
        
    def eventFn_FlightPlan(self, fp):
        self.fp :FlightPlan = pickle.loads(base64.b64decode(fp))
        self.currentWP = None
        print(f"[{self.current_time}] {self.prim_path}: flightplan received")

    def eventFn_ResetControl(self):
        self.x  = np.zeros((8, 1))  # model state
        self.y  = np.zeros((4, 1))  # model output
        self.u  = np.zeros((4, 1))  # input (rotors speeds)
        self.r  = np.zeros((4, 1))  # model reference
        self.e  = np.zeros((4, 1))  # model error
        self.E  = np.zeros((4, 1))  # model accumulated error
            
    #------------------------------------------------------------------------------------------------------------------
    # FLYING FUNCTIONS

    def rotors_off(self):
        # Apagamos motores
        self.w_rotor_NE = 0
        self.w_rotor_NW = 0
        self.w_rotor_SE = 0
        self.w_rotor_SW = 0

        # Reset del control
        self.E = np.zeros((4, 1))

    def imu(self):
        # Get position and rotation of all UAV links
        pos, rot = self.rigid_prim_view.get_world_poses()
        pos2, rot2 = self.rigid_prim_view.get_local_poses()

        print("R1:\n", rot)
        print("R2:\n", rot2)

        self.body_link_pos = pos[0]
        self.body_link_rot = Rotation.from_quat([rot[0][1], rot[0][2], rot[0][3], rot[0][0]])

        self.NE_rotor_link_pos = pos[1]
        self.NE_rotor_link_rot = Rotation.from_quat([rot[1][1], rot[1][2], rot[1][3], rot[1][0]])

        self.NW_rotor_link_pos = pos[2]
        self.NW_rotor_link_rot = Rotation.from_quat([rot[2][1], rot[2][2], rot[2][3], rot[2][0]])

        self.SE_rotor_link_pos = pos[3]
        self.SE_rotor_link_rot = Rotation.from_quat([rot[3][1], rot[3][2], rot[3][3], rot[3][0]])

        self.SW_rotor_link_pos = pos[4]
        self.SW_rotor_link_rot = Rotation.from_quat([rot[4][1], rot[4][2], rot[4][3], rot[4][0]])

        # Get body_link roll, pitch and yaw in euler angles
        self.roll, self.pitch, self.yaw = self.body_link_rot.as_euler('xyz', degrees=False)

        # Get linear and angular velocities of all UAV links
        lin = self.rigid_prim_view.get_linear_velocities()
        ang = self.rigid_prim_view.get_angular_velocities()

        self.body_link_lin = lin[0]
        self.body_link_ang = ang[0]

        self.NE_rotor_link_lin = lin[1]
        self.NE_rotor_link_ang = ang[1]

        self.NW_rotor_link_lin = lin[2]
        self.NW_rotor_link_ang = ang[2]

        self.SE_rotor_link_lin = lin[3]
        self.SE_rotor_link_ang = ang[3]

        self.SW_rotor_link_lin = lin[4]
        self.SW_rotor_link_ang = ang[4]

        

        # self.pos  = self.pos_atr.Get()
        # # print(f"\nposition:  {self.pos}")

        # ori  = self.ori_atr.Get()
        # # print(f"\norientation:  {self.ori}")
     
        # W = ori.real
        # X = ori.imaginary[0]
        # Y = ori.imaginary[1]
        # Z = ori.imaginary[2]
        # # print(f"Orientation:  {W:.4f} {X:.4f} {Y:.4f} {Z:.4f}")

        # self.rot = Rotation.from_quat([X,Y,Z,W])     
        # self.roll, self.pitch, self.yaw = self.rot.as_euler('xyz', degrees=False)
        # # print(f"Euler RPY (rad):  {self.roll:.2f} {self.pitch:.2f} {self.yaw:.2f}")
        # # roll, pitch, yaw = rot.as_euler('xyz', degrees=True)
        # # print(f"Euler RPY (deg):  {roll:.0f} {pitch:.0f} {yaw:.0f}")

        # self.body_link_lin  = self.linVel_atr.Get()
        # # print(f"linear velocity  (local):  {self.linear_vel}")

        # self.body_link_ang = self.angVel_atr.Get()
        # # print(f"angular velocity (local):  {self.angular_vel}")

    def navigation(self):
        # This function converts a flight plan position at certain time
        # to a navigation command (desired velocity vector and rotation)
        if self.fp is None:
            return

        # Check FP vigency
        WP = self.fp.get_target_index_from_time(self.current_time)
        numWPs = len(self.fp.waypoints)

        if self.currentWP is None and WP != 0:
            # This flight plan is obsolete
            print(f"[{self.current_time:3.2f}] {self.prim_path} discarding FP due to it is obsolete")
            self.fp = None
            return
        
        # Navigation status has changed?
        if self.currentWP != WP:
            if WP == 0:
                initPos = self.fp.waypoints[0].pos.copy()
                initPos -= self.pos

                if np.linalg.norm(initPos) < self.fp.radius:
                    # Drone waiting to start the flight
                    print(f"[{self.current_time:3.2f}] {self.prim_path} waiting to start a FP")

                else:
                    # Drone in an incorrect starting position
                    print(f"[{self.current_time:3.2f}] {self.prim_path} discarding FP due to an incorrect starting position")
                    self.fp = None
                    return

            elif WP < numWPs:
                print(f"[{self.current_time:3.2f}] {self.prim_path} flying to {self.fp.waypoints[WP].label}")

            else:
                print(f"[{self.current_time:3.2f}] {self.prim_path} has completed its flight plan")

                # Uncomment this to show the corresponding plots
                plt.close(plt.gcf())
                self.fp.position_figure("FP1: POSITION", 0.01)
                self.fp.velocity_figure("FP1: VELOCITY", 0.01)
                
                self.fp.add_UAV_track_pos("FP1: POSITION", self.track_info)
                self.fp.add_UAV_track_vel("FP1: VELOCITY", self.track_info)

                self.fp = None
                return

        self.currentWP = WP
        
        # Change relative vel to absolute
        linear_vel = self.rot.apply(self.body_link_lin)
        self.command = self.fp.get_command(self.current_time, self.pos, linear_vel, self.rot, 2)
        self.cmd_exp_time = self.current_time + self.command.duration

    def servo_control(self):
        # This function converts 
        # a navigation command (desired velocity vector and rotation)
        # to speeds of the four rotors

        # print("CURRENT TIME: ", self.current_time)
        # print("self.r")
        # print(self.r)
        # print("self.x")
        # print(self.x)
        # print("self.y")
        # print(self.y)
        # print("self.e")
        # print(self.e)
        # print("self.E")
        # print(self.E)
        # print("self.u")
        # print(self.u)
        # print("\n\n")

        if not self.command.on:
            self.rotors_off()
            return

        if self.command.duration is not None:
            if self.current_time > self.cmd_exp_time:
                self.command.hover()

        # Assign the model reference to be followed
        self.r[0, 0] = self.command.velX        # bXdot
        self.r[1, 0] = self.command.velY        # bYdot
        self.r[2, 0] = self.command.velZ        # bZdot
        self.r[3, 0] = self.command.rotZ        # hZdot
        # print(f"r: {np.round(self.r.T, 2)}")

        # Assign model state
        self.x[0, 0] = self.roll           # ePhi
        self.x[1, 0] = self.pitch          # eTheta
        self.x[2, 0] = self.body_link_ang[0] # bWx
        self.x[3, 0] = self.body_link_ang[1] # bWy
        self.x[4, 0] = self.body_link_ang[2] # bWz
        self.x[5, 0] = self.body_link_lin[0]  # bXdot
        self.x[6, 0] = self.body_link_lin[1]  # bYdot
        self.x[7, 0] = self.body_link_lin[2]  # bZdot
        # print(f"x: {np.round(self.x.T, 2)}")

        # Assign model output
        self.y[0, 0] = self.x[5, 0]        # bXdot
        self.y[1, 0] = self.x[6, 0]        # bYdot
        self.y[2, 0] = self.x[7, 0]        # bZdot
        self.y[3, 0] = self.x[4, 0]        # bWz
        # print(f"y: {np.round(self.y.T, 2)}")

        # Error between the output and the reference 
        # (between the commanded velocity and the drone velocity)
        self.e = self.y - self.r
        # print(f"e: {np.round(self.e.T, 2)}")

        # Cumulative error
        self.E = self.E + (self.e * self.delta_time)
        # print(f"E: {np.round(self.E.T, 2)}")

        # Error saturation
        # if self.E[0, 0] >  self.E_max : self.E[0, 0] =  self.E_max
        # if self.E[0, 0] < -self.E_max : self.E[0, 0] = -self.E_max
        # if self.E[1, 0] >  self.E_max : self.E[1, 0] =  self.E_max
        # if self.E[1, 0] < -self.E_max : self.E[1, 0] = -self.E_max
        # if self.E[2, 0] >  self.E_max : self.E[2, 0] =  self.E_max
        # if self.E[2, 0] < -self.E_max : self.E[2, 0] = -self.E_max
        # if self.E[3, 0] >  self.E_max : self.E[3, 0] =  self.E_max
        # if self.E[3, 0] < -self.E_max : self.E[3, 0] = -self.E_max

        # Dynamic system control
        self.u = self.Hs - self.Kx @ self.x - self.Ky @ self.E
        # print(f"u: {np.round(self.u.T, 2)}")

        # Rotor speed saturation
        if self.u[0, 0] > self.w_max : self.u[0, 0] = self.w_max
        if self.u[0, 0] < self.w_min : self.u[0, 0] = self.w_min
        if self.u[1, 0] > self.w_max : self.u[1, 0] = self.w_max
        if self.u[1, 0] < self.w_min : self.u[1, 0] = self.w_min
        if self.u[2, 0] > self.w_max : self.u[2, 0] = self.w_max
        if self.u[2, 0] < self.w_min : self.u[2, 0] = self.w_min
        if self.u[3, 0] > self.w_max : self.u[3, 0] = self.w_max
        if self.u[3, 0] < self.w_min : self.u[3, 0] = self.w_min

        # Assign rotor speed
        self.w_rotor_NE = self.u[0, 0]
        self.w_rotor_NW = self.u[1, 0]
        self.w_rotor_SE = self.u[2, 0]
        self.w_rotor_SW = self.u[3, 0]

    def platform_dynamics(self):
        FT_NE = np.array([0, 0, self.kFT * self.w_rotor_NE**2])
        FT_NW = np.array([0, 0, self.kFT * self.w_rotor_NW**2])
        FT_SE = np.array([0, 0, self.kFT * self.w_rotor_SE**2])
        FT_SW = np.array([0, 0, self.kFT * self.w_rotor_SW**2])

        # Apply the air friction force to the drone
        FD = np.array([
            -self.kFDx * self.body_link_lin[0] * abs(self.body_link_lin[0]),
            -self.kFDy * self.body_link_lin[1] * abs(self.body_link_lin[1]),
            -self.kFDz * self.body_link_lin[2] * abs(self.body_link_lin[2])])
      
        # Compute the drag moment
        MDR_NE = self.kMDR * self.w_rotor_NE**2
        MDR_NW = self.kMDR * self.w_rotor_NW**2
        MDR_SE = self.kMDR * self.w_rotor_SE**2
        MDR_SW = self.kMDR * self.w_rotor_SW**2
        MDR = np.array([0, 0, MDR_NE - MDR_NW - MDR_SE + MDR_SW])

        # Compute the air friction moment
        MD = np.array([
            -self.kMDx * self.body_link_ang[0] * abs(self.body_link_ang[0]),
            -self.kMDy * self.body_link_ang[1] * abs(self.body_link_ang[1]),
            -self.kMDz * self.body_link_ang[2] * abs(self.body_link_ang[2])])

        # Apply the moments to the drone
        body_link_torque = MDR + MD
        zero_torque = np.array([0, 0, 0])

        forces = np.array([FD, FT_NE, FT_NW, FT_SE, FT_SW])
        torques = np.array([body_link_torque, zero_torque, zero_torque, zero_torque, zero_torque])
        self.rigid_prim_view.apply_forces_and_torques_at_pos(forces=forces, torques=torques, is_global=False)

    #------------------------------------------------------------------------------------------------------------------
    # TRACKING FUNCTIONS

    def telemetry(self):
        # Update every self.refresh_rate seconds
        if self.current_time - self.last_time_track >= self.refresh_rate:
            # Update last_time_track
            self.last_time_track = self.current_time

            # Change relative vel to absolute
            linear_vel = self.rot.apply(self.linear_vel)

            # Get tracking information
            self.track_info.append(Waypoint(t= self.current_time, pos=self.pos, vel=linear_vel))

            # Check if we want to show tracking while simulating
            # if self.show_tracking:
            #     # Check if we already built the figure
            #     if not self.tracking_figure_builded:
            #         # Build the ploting figure just once
            #         self.tracking_figure_builded = True

            #         # Create the matplotlib figure and the corresponding plot
            #         track_fig = plt.figure("Tracking Plot")
            #         self.track_plot = track_fig.add_subplot(projection="3d")

            #         # Indicate the axes name
            #         self.track_plot.set_xlabel("x [m]")
            #         self.track_plot.set_ylabel("y [m]")
            #         self.track_plot.set_zlabel("z [m]")

            #         # Write a title for the plot
            #         self.track_plot.set_title("Position 3D")

            #         # Stablish the initial limits
            #         # self.track_plot.set_xlim3d(-15, 15)
            #         # self.track_plot.set_ylim3d(-15, 15)
            #         # self.track_plot.set_zlim3d(-15, 15)

            #         # Plot initial position
            #         self.line, = self.track_plot.plot(self.xPos_track, self.yPos_track, self.zPos_track, 
            #                                           linestyle="dashed", linewidth=1, color="black")

            #     self.line.set_data(self.xPos_track, self.yPos_track)
            #     self.line.set_3d_properties(self.zPos_track)
            #     self.track_plot.scatter(self.xPos_track[-1], self.yPos_track[-1], self.zPos_track[-1], color="black", 
            #                             s=10)

            #     # Update plot limits
            #     track_plot_lims = self.get_matplotlib_plot_limits(self.track_plot)
            #     new_limits = self.update_track_plot_lims(track_plot_lims, self.pos)

            #     self.track_plot.set_xlim3d(*new_limits[0])
            #     self.track_plot.set_ylim3d(*new_limits[1])
            #     self.track_plot.set_zlim3d(*new_limits[2])

            #     plt.pause(0.01)

    def get_matplotlib_plot_limits(self, plot):
        try:
            z_lim = plot.get_zlim3d()
            x_lim = plot.get_xlim3d()
            y_lim = plot.get_ylim3d()

            return [x_lim, y_lim, z_lim]
        
        except:
            x_lim = plot.get_xlim3d()
            y_lim = plot.get_ylim3d()

            return (x_lim, y_lim)
        
    def update_track_plot_lims(self, track_plot_lims, new_pos):
        if new_pos[0] < track_plot_lims[0][0]:
            track_plot_lims[0] = [new_pos[0], track_plot_lims[0][1]]

        if new_pos[0] > track_plot_lims[0][1]:
            track_plot_lims[0] = [track_plot_lims[0][0], new_pos[0]]

        if new_pos[1] < track_plot_lims[1][0]:
            track_plot_lims[1] = [new_pos[1], track_plot_lims[1][1]]

        if new_pos[1] > track_plot_lims[1][1]:
            track_plot_lims[1] = [track_plot_lims[1][0], new_pos[1]]

        if new_pos[2] < track_plot_lims[2][0]:
            track_plot_lims[2] = [new_pos[2], track_plot_lims[2][0]]

        if new_pos[2] > track_plot_lims[2][1]:
            track_plot_lims[2] = [track_plot_lims[2][0], new_pos[2]]

        return track_plot_lims