[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
category = "Simulation"
title = "navsim"
description = ""
authors = ["Víctor Blázquez Milara", "Iker Nebot Amoriza", "Rafael Casado González", "Aurelio Bermúdez Marín"]
repository = ""
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"


[dependencies]
"omni.kit.uiapp" = {}
"isaacsim.gui.components" = {}
"isaacsim.core.api" = {}

[[python.module]]
name = "uspace_vertiports_python"