# config/mosquitto.conf

# -----------------------------------------------------------------
# Core Settings
# -----------------------------------------------------------------
persistence false

# -----------------------------------------------------------------
# Listeners & Security
# -----------------------------------------------------------------
# Listen on the default MQTT port
listener 1883

# Enable anonymous access
allow_anonymous true
