# Standard library imports
import sys
import os
import pickle   # Serialization
import base64   # Parsing to string

# Related third party imports
import omni.kit.app
import carb.events
import numpy as np
import matplotlib.pyplot as plt
from omni.isaac.core.prims import RigidPrimView
from omni.kit.scripting import BehaviorScript
from pxr import Sdf, Gf
from scipy.spatial.transform import Rotation


# Adding root 'ov' folder to sys.path
current_path = os.path.abspath(os.path.dirname(__file__))
while True:
    if os.path.basename(current_path) == 'ov':
        project_root_path = current_path
        break
    parent_path = os.path.dirname(current_path)
    if parent_path == current_path:
        raise RuntimeError("No se encontró el directorio 'ov' en la ruta.")
    current_path = parent_path

if project_root_path not in sys.path:
    sys.path.append(project_root_path)


# Local application/library specific imports
from uspace.flight_plan.flight_plan import FlightPlan
from uspace.flight_plan.waypoint import Waypoint
from uspace.flight_plan.command import Command


class UAM_minidrone(BehaviorScript):

    def on_init(self):
        self.current_time = 0
        self.delta_time = 0

        # Create rigid prim view
        prim_paths = ["/aerotaxi/body_link", "/aerotaxi/(NE|NW|SE|SW)_rotor_link"]
        self.rigid_prim_view = RigidPrimView(prim_paths)
        self.rigid_prim_view_initialized = False
        
        # Create the omniverse event associated to this UAV
        self.UAV_EVENT = carb.events.type_from_string("NavSim." + str(self.prim.GetPath()))
        bus = omni.kit.app.get_app().get_message_bus_event_stream()
        self.eventSub = bus.create_subscription_to_push_by_type(self.UAV_EVENT, self.push_subscripted_event_method)

        #--------------------------------------------------------------------------------------------------------------
        # NAVIGATION PARAMETERS

        self.fp = None               
        self.currentWP = None  

        # AutoPilot navigation command
        self.command = Command()
        self.cmd_exp_time = 0

        # Tracking
        self.tracking_figure_builded = False
        self.refresh_rate = 1
        self.last_time_track = 0
        self.track_info = []

        #--------------------------------------------------------------------------------------------------------------
        # AEROTAXI PARAMETERS

        self.g = 9.81

        self.body_link_pos = np.array([0, 0, 0])
        self.roll = 0
        self.pitch = 0
        self.yaw = 0
        self.body_link_lin = np.array([0, 0, 0])
        self.body_link_ang = np.array([0, 0, 0])

        # Rotors speed (rad/s)
        self.w_rotor_NE = 0.0
        self.w_rotor_NW = 0.0
        self.w_rotor_SE = 0.0
        self.w_rotor_SW = 0.0
    
        # Max and minimum angular velocity of the motors
        self.w_max = 62.8319 # rad/s = 600rpm
        self.w_min = 0 # rad/s = 0rpm

        # Aerodynamic thrust force constant
        # Force generated by the rotors is FT = kFT * w²
        self.kFT_N = 4.6544 # North side
        self.kFT_S = 0.9309 # South side
        self.w_hov = 41.8879 # rad/s = 400rpm

        # Aerodynamic drag force constant
        # Moment generated by the rotors is MDR = kMDR * w²
        self.kMDR_N = 5.9683
        self.kMDR_S = 1.4921

        # Aerodynamic drag force constant per axis
        # Drag force generated by the air friction, opposite to the velocity is FD = -kFD * r_dot*|r_dot|
        # Horizontal axis:
        self.kFDx = 3.0625
        self.kFDy = 4.0000
        # Vertical axis:
        self.kFDz = 7.8400

        # Aerodynamic drag moment constant per axis
        # Drag moment generated by the air friction, opposite to the angular velocity is MD = -kMD * rpy_dot*|rpy_dot|
        self.kMDx = 37.4010
        self.kMDy = 25.8580
        self.kMDz = 20.2514

        #--------------------------------------------------------------------------------------------------------------
        # LOW LEVEL CONTROL

        self.x  = np.zeros((8, 1)) # Model state
        self.y  = np.zeros((4, 1)) # Model output
        self.u  = np.zeros((4, 1)) # Input (rotors speeds)
        self.r  = np.zeros((4, 1)) # Model reference
        self.e  = np.zeros((4, 1)) # Model error
        self.E  = np.zeros((4, 1)) # Model accumulated error
        
        # State control matrix
        self.Kx = np.array([
            [ -14.6551,  -45.5032,   -4.1872,  -13.0009,    3.8871,   -6.6331,    2.1363,    6.4114 ],
            [  14.6551,  -45.5032,    4.1872,  -13.0009,   -3.8871,   -6.6331,   -2.1363,    6.4114 ],
            [ -58.6206,  227.5161,  -16.7487,   65.0046,  -24.4514,   33.1656,    8.5453,    6.4114 ],
            [  58.6206,  227.5161,   16.7487,   65.0046,   24.4514,   33.1656,   -8.5453,    6.4114 ]
        ])

        # Error control matrix
        self.Ky = np.array([
            [ -3.1839,    1.0254,    4.2743,    2.5914 ],
            [ -3.1839,   -1.0254,    4.2743,   -2.5914 ],
            [ 15.9195,    4.1017,    4.2743,  -16.3009 ],
            [ 15.9195,   -4.1017,    4.2743,   16.3009 ]           
        ])

        # Hovering speed
        self.Hs = np.array([
            [self.w_hov], 
            [self.w_hov], 
            [self.w_hov], 
            [self.w_hov]
        ])
        
        # Maximum model accumulated error
        self.E_max = 150
    
    def on_destroy(self):
        self.uav_event_sub = None
    
    #------------------------------------------------------------------------------------------------------------------
    # EVENT HANDLERS

    def on_play(self):
        # Tracking
        self.show_tracking = False
        self.refresh_rate = 1
        self.last_time_track = 0

        # Update the drone status
        self.imu()
        self.navigation()
        self.servo_control()
        self.platform_dynamics()
        self.telemetry()

    def on_pause(self):
        pass

    def on_stop(self):
        self.rigid_prim_view_initialized = False
        self.current_time = 0
        self.delta_time = 0

        self.command.off()
        self.rotors_off()
    
        self.fp = None

        self.tracking_figure_builded = False
        self.track_info = []

    def on_update(self, current_time: float, delta_time: float):
        if not self.rigid_prim_view_initialized:
            self.rigid_prim_view.initialize()
            self.rigid_prim_view_initialized = True
        
        # Get current simulation time
        self.current_time = current_time
        self.delta_time = delta_time

        # Update the drone status
        self.imu()
        self.navigation()
        self.servo_control()
        self.platform_dynamics()
        self.telemetry()

    def push_subscripted_event_method(self, e):       

        try:
            method = getattr(self, e.payload["method"]) 
        except:
            print(f"Method {e.payload['method']} not found")
            return
        
        match e.payload["method"]:
            case "eventFn_RemoteCommand":
                method(e.payload["command"])
            case "eventFn_FlightPlan":
                method(e.payload["fp"])
            case _:
                method()
            
    def eventFn_RemoteCommand(self, command):
        self.command : Command = pickle.loads(base64.b64decode(command))
        if self.command.duration is not None:
            self.cmd_exp_time = self.current_time + self.command.duration
            print(f"[{self.current_time}] {self.prim_path}: command received")
        
    def eventFn_FlightPlan(self, fp):
        self.fp :FlightPlan = pickle.loads(base64.b64decode(fp))
        self.currentWP = None
        print(f"[{self.current_time}] {self.prim_path}: flightplan received")
            
    #------------------------------------------------------------------------------------------------------------------
    # FLYING FUNCTIONS

    def rotors_off(self):
        # Turn off rotors
        self.w_rotor_NE = 0
        self.w_rotor_NW = 0
        self.w_rotor_SE = 0
        self.w_rotor_SW = 0

        # Reset control
        self.E = np.zeros((4, 1))

    def imu(self):
        # Get position and rotation of all UAV links
        pos, rot = self.rigid_prim_view.get_world_poses()

        self.body_link_pos = pos[0]
        self.body_link_rot = Rotation.from_quat([rot[0][1], rot[0][2], rot[0][3], rot[0][0]])

        self.NE_rotor_link_pos = pos[1]
        self.NE_rotor_link_rot = Rotation.from_quat([rot[1][1], rot[1][2], rot[1][3], rot[1][0]])

        self.NW_rotor_link_pos = pos[2]
        self.NW_rotor_link_rot = Rotation.from_quat([rot[2][1], rot[2][2], rot[2][3], rot[2][0]])

        self.SE_rotor_link_pos = pos[3]
        self.SE_rotor_link_rot = Rotation.from_quat([rot[3][1], rot[3][2], rot[3][3], rot[3][0]])

        self.SW_rotor_link_pos = pos[4]
        self.SW_rotor_link_rot = Rotation.from_quat([rot[4][1], rot[4][2], rot[4][3], rot[4][0]])

        # Get body_link roll, pitch and yaw in euler angles
        self.roll, self.pitch, self.yaw = self.body_link_rot.as_euler('xyz', degrees=False)

        # Get linear and angular velocities of all UAV links
        lin = self.rigid_prim_view.get_linear_velocities()
        ang = self.rigid_prim_view.get_angular_velocities()

        self.body_link_lin = lin[0]
        self.body_link_ang = ang[0]

        self.NE_rotor_link_lin = lin[1]
        self.NE_rotor_link_ang = ang[1]

        self.NW_rotor_link_lin = lin[2]
        self.NW_rotor_link_ang = ang[2]

        self.SE_rotor_link_lin = lin[3]
        self.SE_rotor_link_ang = ang[3]

        self.SW_rotor_link_lin = lin[4]
        self.SW_rotor_link_ang = ang[4]

    def navigation(self):
        # This function converts a flight plan position at certain time to a navigation command
        if self.fp is None:
            return

        # Check FP vigency
        WP = self.fp.get_target_index_from_time(self.current_time)
        numWPs = len(self.fp.waypoints)

        if self.currentWP is None and WP != 0:
            # This flight plan is obsolete
            print(f"[{self.current_time:3.2f}] {self.prim_path} discarding FP due to it is obsolete")
            self.fp = None
            return
        
        # Navigation status has changed?
        if self.currentWP != WP:
            if WP == 0:
                initPos = self.fp.waypoints[0].pos.copy()
                initPos -= self.body_link_pos

                if np.linalg.norm(initPos) < self.fp.radius:
                    # Drone waiting to start the flight
                    print(f"[{self.current_time:3.2f}] {self.prim_path} waiting to start a FP")

                else:
                    # Drone in an incorrect starting position
                    print(f"[{self.current_time:3.2f}] {self.prim_path} discarding FP due to an incorrect starting position")
                    self.fp = None
                    return

            elif WP < numWPs:
                print(f"[{self.current_time:3.2f}] {self.prim_path} flying to {self.fp.waypoints[WP].label}")

            else:
                print(f"[{self.current_time:3.2f}] {self.prim_path} has completed its flight plan")
                self.fp = None
                return

        self.currentWP = WP
        
        # Change relative vel to absolute
        linear_vel = self.body_link_rot.apply(self.body_link_lin)
        self.command = self.fp.get_command(self.current_time, self.body_link_pos, linear_vel, self.body_link_rot, 2)
        self.cmd_exp_time = self.current_time + self.command.duration

    def servo_control(self):
        # This function converts a navigation command into speeds of the four rotors
        if not self.command.on:
            self.rotors_off()
            return

        if self.command.duration is not None:
            if self.current_time > self.cmd_exp_time:
                self.command.hover()

        # Assign the model reference to be followed
        self.r[0, 0] = self.command.velX       # bXdot
        self.r[1, 0] = self.command.velY       # bYdot
        self.r[2, 0] = self.command.velZ       # bZdot
        self.r[3, 0] = self.command.rotZ       # hZdot

        # Assign model state
        self.x[0, 0] = self.roll           # ePhi
        self.x[1, 0] = self.pitch          # eTheta
        self.x[2, 0] = self.body_link_ang[0] # bWx
        self.x[3, 0] = self.body_link_ang[1] # bWy
        self.x[4, 0] = self.body_link_ang[2] # bWz
        self.x[5, 0] = self.body_link_lin[0]  # bXdot
        self.x[6, 0] = self.body_link_lin[1]  # bYdot
        self.x[7, 0] = self.body_link_lin[2]  # bZdot

        # Assign model output
        self.y[0, 0] = self.x[5, 0]        # bXdot
        self.y[1, 0] = self.x[6, 0]        # bYdot
        self.y[2, 0] = self.x[7, 0]        # bZdot
        self.y[3, 0] = self.x[4, 0]        # bWz

        # Error between the output and the reference (between the commanded velocity and the drone velocity)
        self.e = self.y - self.r

        # Cumulative error
        self.E = self.E + (self.e * self.delta_time)

        # Error saturation
        # if self.E[0, 0] >  self.E_max : self.E[0, 0] =  self.E_max
        # if self.E[0, 0] < -self.E_max : self.E[0, 0] = -self.E_max
        # if self.E[1, 0] >  self.E_max : self.E[1, 0] =  self.E_max
        # if self.E[1, 0] < -self.E_max : self.E[1, 0] = -self.E_max
        # if self.E[2, 0] >  self.E_max : self.E[2, 0] =  self.E_max
        # if self.E[2, 0] < -self.E_max : self.E[2, 0] = -self.E_max
        # if self.E[3, 0] >  self.E_max : self.E[3, 0] =  self.E_max
        # if self.E[3, 0] < -self.E_max : self.E[3, 0] = -self.E_max

        # Dynamic system control
        self.u = self.Hs - self.Kx @ self.x - self.Ky @ self.E

        # Rotor speed saturation
        if self.u[0, 0] > self.w_max : self.u[0, 0] = self.w_max
        if self.u[0, 0] < self.w_min : self.u[0, 0] = self.w_min
        if self.u[1, 0] > self.w_max : self.u[1, 0] = self.w_max
        if self.u[1, 0] < self.w_min : self.u[1, 0] = self.w_min
        if self.u[2, 0] > self.w_max : self.u[2, 0] = self.w_max
        if self.u[2, 0] < self.w_min : self.u[2, 0] = self.w_min
        if self.u[3, 0] > self.w_max : self.u[3, 0] = self.w_max
        if self.u[3, 0] < self.w_min : self.u[3, 0] = self.w_min

        # Assign rotor speed
        self.w_rotor_NE = self.u[0, 0]
        self.w_rotor_NW = self.u[1, 0]
        self.w_rotor_SE = self.u[2, 0]
        self.w_rotor_SW = self.u[3, 0]

    def platform_dynamics(self):
        # Translate rotor speeds into forces and moments of the free solid to simulate lift rotation.
        # Apply thrust force
        FT_NE = np.array([0, 0, self.kFT_N * self.w_rotor_NE**2])
        FT_NW = np.array([0, 0, self.kFT_N * self.w_rotor_NW**2])
        FT_SE = np.array([0, 0, self.kFT_S * self.w_rotor_SE**2])
        FT_SW = np.array([0, 0, self.kFT_S * self.w_rotor_SW**2])

        # Apply the air friction force to the aerotaxi
        FD = np.array([
            -self.kFDx * self.body_link_lin[0] * abs(self.body_link_lin[0]),
            -self.kFDy * self.body_link_lin[1] * abs(self.body_link_lin[1]),
            -self.kFDz * self.body_link_lin[2] * abs(self.body_link_lin[2])])
        # self.force_atr.Set(FD)
      
        # Compute the drag moment
        MDR_NE = self.kMDR_N * self.w_rotor_NE**2
        MDR_NW = self.kMDR_N * self.w_rotor_NW**2
        MDR_SE = self.kMDR_S * self.w_rotor_SE**2
        MDR_SW = self.kMDR_S * self.w_rotor_SW**2
        MDR = np.array([0, 0, MDR_NE - MDR_NW - MDR_SE + MDR_SW])

        # Compute the air friction moment
        MD = np.array([
            -self.kMDx * self.body_link_ang[0] * abs(self.body_link_ang[0]),
            -self.kMDy * self.body_link_ang[1] * abs(self.body_link_ang[1]),
            -self.kMDz * self.body_link_ang[2] * abs(self.body_link_ang[2])])

        # Compute drone moment
        body_link_torque = MDR + MD
        zero_torque = np.array([0, 0, 0])

        # Apply forces and torques to all UAV links
        forces = np.array([FD, FT_NE, FT_NW, FT_SE, FT_SW])
        torques = np.array([body_link_torque, zero_torque, zero_torque, zero_torque, zero_torque])
        self.rigid_prim_view.apply_forces_and_torques_at_pos(forces=forces, torques=torques)

    #------------------------------------------------------------------------------------------------------------------
    # TRACKING FUNCTIONS

    def telemetry(self):
        # Update every self.refresh_rate seconds
        if self.current_time - self.last_time_track >= self.refresh_rate:
            # Update last_time_track
            self.last_time_track = self.current_time

            # Change relative vel to absolute
            linear_vel = self.body_link_rot.apply(self.body_link_lin)

            # Get tracking information
            self.track_info.append(Waypoint(t=self.current_time, pos=self.body_link_pos, vel=linear_vel))

    def get_matplotlib_plot_limits(self, plot):
        try:
            z_lim = plot.get_zlim3d()
            x_lim = plot.get_xlim3d()
            y_lim = plot.get_ylim3d()
            return [x_lim, y_lim, z_lim]
        
        except:
            x_lim = plot.get_xlim3d()
            y_lim = plot.get_ylim3d()
            return (x_lim, y_lim)
        
    def update_track_plot_lims(self, track_plot_lims, new_pos):
        if new_pos[0] < track_plot_lims[0][0]:
            track_plot_lims[0] = [new_pos[0], track_plot_lims[0][1]]

        if new_pos[0] > track_plot_lims[0][1]:
            track_plot_lims[0] = [track_plot_lims[0][0], new_pos[0]]

        if new_pos[1] < track_plot_lims[1][0]:
            track_plot_lims[1] = [new_pos[1], track_plot_lims[1][1]]

        if new_pos[1] > track_plot_lims[1][1]:
            track_plot_lims[1] = [track_plot_lims[1][0], new_pos[1]]

        if new_pos[2] < track_plot_lims[2][0]:
            track_plot_lims[2] = [new_pos[2], track_plot_lims[2][0]]

        if new_pos[2] > track_plot_lims[2][1]:
            track_plot_lims[2] = [track_plot_lims[2][0], new_pos[2]]
            
        return track_plot_lims