[core]
reloadable = true
order = 0

[package]
version = "1.0.2"
category = "Simulation"
title = "NavSim External Control"
description="External input controller for manipulable prims"
authors = ["I3A-NavSys"]
repository = ""
keywords = ["controller", "UAV", "dron"]
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.ui" = {}
"omni.isaac.core" = {}
# PyQt5 pipapi
# pygame pipapi

[[python.module]]
name = "external_control_python"
