[core]
order = 1000

[package]
version = "1.0.0"

authors = ["NavSys"]

title = "multi_manual_controller"
description="A simple python extension example to use as a starting point for your extensions."

readme  = "docs/README.md"

repository = ""

category = "Other"

keywords = ["kit", "example"]

changelog="docs/CHANGELOG.md"

preview_image = "data/preview.png"

icon = "data/icon.png"

[dependencies]
"omni.kit.uiapp" = {}

[python.pipapi]
requirements = [
    "tabulate", 
    "pygame",
]
use_online_index = true

[[python.module]]
name = "multi_manual_controller_python"