version: '3.8'
services:
  mqtt_dtblock:
    image: eclipse-mosquitto:2.0
    container_name: Integrador_MQTT
    restart: unless-stopped
    ports:
      - "${MQTT_HOST_ADDRESS}:${MQTT_HOST_PORT}:1883"
    volumes:
      - ../../mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

  uspace_manager_dtblock:
    build:
      context: ../../
      dockerfile: platgdia/dtblocks/uspace_manager/dockerfile
    container_name: Gestor_de_espacio_aereo
    restart: unless-stopped
    depends_on:
      - mqtt_dtblock
    environment:
      - MQTT_HOST_ADDRESS=${MQTT_HOST_ADDRESS}
      - MQTT_HOST_PORT=${MQTT_HOST_PORT}

  vertiport_operator_dtblock:
    build:
      context: ../../
      dockerfile: platgdia/dtblocks/vertiport_operator/dockerfile
    container_name: Operador_de_vertipuertos
    restart: unless-stopped
    depends_on:
      - uspace_manager_dtblock
    environment:
      - MQTT_HOST_ADDRESS=${MQTT_HOST_ADDRESS}
      - MQTT_HOST_PORT=${MQTT_HOST_PORT}

  uav_operator_dtblock:
    build:
      context: ../../
      dockerfile: platgdia/dtblocks/uav_operator/dockerfile
    container_name: Operador_de_UAVs
    restart: unless-stopped
    depends_on:
      - uspace_manager_dtblock
      - vertiport_operator_dtblock
    environment:
      - MQTT_HOST_ADDRESS=${MQTT_HOST_ADDRESS}
      - MQTT_HOST_PORT=${MQTT_HOST_PORT}

  mission_manager_dtblock:
    build:
      context: ../../
      dockerfile: platgdia/dtblocks/mission_manager/dockerfile
    container_name: Gestor_de_clientes_UAM
    restart: unless-stopped
    depends_on:
      - uspace_manager_dtblock
      - uav_operator_dtblock
    environment:
      - MQTT_HOST_ADDRESS=${MQTT_HOST_ADDRESS}
      - MQTT_HOST_PORT=${MQTT_HOST_PORT}

volumes:
  mosquitto-data:
  mosquitto-log: