# =============================================================================
# GLOBAL CONFIGURATION: UAV 4D Conflict Resolver
# =============================================================================
# All tunable parameters for the resolution pipeline are centralized here.
# Changing these values affects every phase of the resolution cascade.
# =============================================================================

# -----------------------------------------------------------------------------
# NUMERICAL TOLERANCES
# These were originally defined in detection/conflictDetection.py.
# They are centralised here so that all modules share a single source of truth.
#
# EPSILON_ABSOLUTE:   Detects pure numerical instabilities (values near zero).
#                     Used for near-zero norm/axis checks throughout SAT.
#
# EPSILON_ORTHOGONAL: Validates orthonormality of rotation matrices and unit
#                     vectors. Required by the SAT algorithm.
#
# EPSILON_RELATIVE:   Accounts for cascading floating-point errors that scale
#                     with operand magnitude. For UAVs operating in the 1–100 m
#                     range, 1 mm (1e-3) tolerance is acceptable.
# -----------------------------------------------------------------------------
EPSILON_ABSOLUTE:   float = 1e-9   # Near-zero detection (numerical noise floor)
EPSILON_ORTHOGONAL: float = 1e-6   # Orthonormality / unit-vector validation
EPSILON_RELATIVE:   float = 1e-3   # Scaled tolerance for collision comparisons [m]

# Derived tolerance used inline inside collides_with() [see conflictDetection.py].
# Pre-calculated for the typical ~100 m UAV operating scale.
SAT_EPSILON: float = max(EPSILON_ABSOLUTE, EPSILON_RELATIVE * 100)

# General-purpose near-zero check for position/velocity norms across all modules.
# Reuse EPSILON_ABSOLUTE for this — defined as a readable alias.
NORM_ZERO_THRESHOLD: float = EPSILON_ABSOLUTE   # alias: np.linalg.norm(x) < this → zero

# Small time gap inserted between adjacent waypoints to avoid overwriting existing
# entries when using set_waypoint() or postpone_from() with an offset.
WAYPOINT_TIME_EPSILON: float = 0.001   # [s]

# Numerical stabiliser used as a denominator guard in division operations.
# Prevents division-by-zero in ramp alpha calculations.
DIV_EPSILON: float = 1e-12

# -----------------------------------------------------------------------------
# WCET ANCHOR (Temporal Safety)
# The computation always starts at t_anchor = max(t_conflict, t_start) + ANCHOR_DELTA.
# ANCHOR_DELTA = WCET + SAFETY_MARGIN ensures the drone has enough time to receive
# the new plan before the maneuver is physically needed.
# NEVER plan a maneuver at t=0 or before the UAV's scheduled departure (t_start).
# -----------------------------------------------------------------------------
WCET_SECONDS:           float = 2.0   # Worst-Case Execution Time of the resolver [s]
SAFETY_MARGIN_SECONDS:  float = 1.0   # Additional buffer on top of WCET [s]
ANCHOR_DELTA:           float = WCET_SECONDS + SAFETY_MARGIN_SECONDS  # = 3.0 s

# -----------------------------------------------------------------------------
# STRATEGY 1: Kinematic Bounding (Velocity Adjustment via ConnectURM2)
#
# ConnectURM2 connects two waypoints in a straight line at a constant scalar
# speed v.  The temporal displacement (delay or advance) is propagated to ALL
# future waypoints ("Ripple Effect").  This avoids the anomalous trajectories
# generated by polynomial interpolation when speed changes but timestamps
# remain fixed.
#
# MAX_ITERATIONS:          The step search tries at most this many speed
#                          candidates linearly interpolated between the target
#                          and the current speed.
#
#
# S1_MIN_SPEED:            Absolute minimum cruise speed. The Step Search will
#                          never propose a speed below this value [m/s].
#
# RECTILINEAR_THRESHOLD:   Norm threshold for the kinematic guard clause.
#                          If any higher-order derivative (acel, jerk, snap,
#                          crakle) exceeds this value, the segment is considered
#                          curved and Strategy 1 bails out immediately [m/s^n].
#
# MIN_SPEED_CHANGE:        Minimum |Δv| below which a candidate is skipped
#                          (noise floor) [m/s].
#
# VIP_SPEED_SAMPLE_DELTA:  Time offset [s] to sample the VIP's velocity when
#                          its speed at t_anchor is zero (hovering).
#
# CLEARANCE_TIME_BUFFER:   Extra time buffer [s] added/subtracted to the target
#                          arrival time when computing the required speed for
#                          ACCELERATE/BRAKE manoeuvres.
# -----------------------------------------------------------------------------
MAX_ITERATIONS:          int   = 3     # Step search iterations

S1_MIN_SPEED:            float = 0.5   # Absolute minimum speed [m/s]
RECTILINEAR_THRESHOLD:   float = 1e-6  # Guard clause: curved segment detection

MIN_SPEED_CHANGE:        float = 0.01  # Minimum Δv to bother evaluating [m/s]
VIP_SPEED_SAMPLE_DELTA:  float = 0.1   # VIP speed fallback sample offset [s]
CLEARANCE_TIME_BUFFER:   float = 0.5   # Extra separation time buffer [s]

# -----------------------------------------------------------------------------
# STRATEGY 2 / FALLBACK 1: SAT MTV Generation
# After Strategy 1 fails, the resolver computes one MTV per SAT axis by re-running
# the 15-axis SAT loop (3 plebeian OBB axes + 3 VIP OBB axes + 9 cross products).
# This gives up to 15 independent displacement candidates, one per axis.
# Each MTV is multiplied by SAFETY_MTV_SCALE to add a small clearance margin
# beyond the bare minimum separation distance.
# The candidates are split into:
#   - Horizontal_MTVs (XY-dominant): tried by Strategy 2 (Path Stretch)
#   - Vertical_MTVs  (Z-dominant):   tried by Fallback 1 (Vertical MTVs)
# Both lists are sorted ascending by magnitude (minimum disruption first).
#
# DETOUR_APEX_TIME_FRACTION:   Fraction of the inter-waypoint time budget used
#                              to reach the spatial detour apex.
# DETOUR_RETURN_TIME_FRACTION: Fraction at which the return waypoint is placed.
#                              Must satisfy: APEX < RETURN < 1.0
# -----------------------------------------------------------------------------
SAFETY_MTV_SCALE:            float = 1.05  # 5% margin beyond bare minimum [dimensionless]
DETOUR_APEX_TIME_FRACTION:   float = 0.40  # 40% to detour apex
DETOUR_RETURN_TIME_FRACTION: float = 0.75  # 75% to return point

# -----------------------------------------------------------------------------
# FALLBACK 2: Time-Shift (Hovering)
# The plebeian UAV brakes to 0 m/s at t_anchor and hovers in increments of
# HOVER_TIME_STEP until the R-Tree confirms the path is clear.
# HOVER_MAX_TIMEOUT is the hard cutoff to prevent infinite loops.
# -----------------------------------------------------------------------------
HOVER_MAX_TIMEOUT: float = 60.0   # Maximum hovering duration before DEADLOCK [s]
HOVER_TIME_STEP:   float = 0.5    # Time increment per hovering iteration [s]

# -----------------------------------------------------------------------------
# R-TREE / OBB SAMPLING
# Interval used when (re)generating swept OBB boxes for R-Tree registration.
# Smaller = more boxes = more precise detection but higher memory usage.
# -----------------------------------------------------------------------------
OBB_INTERVAL: float = 0.5   # Sampling interval for OBB box generation [s]

# -----------------------------------------------------------------------------
# BÉZIER CONVEX HULL — TRAPEZOID DETOUR
#
# When Strategy 2 or Fallback 1 builds a spatial detour they now create a
# TRAPEZOID (anc → det1 → det2 → ret) instead of a triangle (anc → det → ret).
# This gives the flat middle segment (det1 → det2) enough time to satisfy the
# Bézier Convex Hull Property without requiring extreme velocities, and avoids
# the Fly-By / Corner-Cutting problem of the two-OBB approach.
#
# Time fractions are expressed as a fraction of the available time budget
# between t_anchor and the next original waypoint (t_to_next):
#
#   [t_anchor ─────────────── next_wp.t]   (time_budget = t_to_next)
#       ↑anc   ↑det1    ↑det2  ↑ret
#       0%     20%      60%    80%     (100% = next_wp.t)
#
# TRAP_DETOUR_RAMP_IN_FRACTION:  time fraction at which det1 is placed
#   (end of the ramp-in leg, start of the flat top).
# TRAP_DETOUR_TOP_END_FRACTION:  time fraction at which det2 is placed
#   (end of the flat top, start of the ramp-out leg).
# TRAP_DETOUR_RAMP_OUT_FRACTION: time fraction at which the return waypoint
#   (ret) is placed (end of the ramp-out leg, UAV rejoins original route).
#
# BEZIER_HULL_REDUCTION_FACTOR: multiplicative speed reduction applied each
#   iteration of the velocity-reduction safety loop.
# BEZIER_HULL_MAX_REDUCTIONS:   maximum number of speed reduction iterations
#   before giving up and declaring the detour infeasible.
# -----------------------------------------------------------------------------
TRAP_DETOUR_RAMP_IN_FRACTION:   float = 0.20   # det1 at 20 % of time budget
TRAP_DETOUR_TOP_END_FRACTION:   float = 0.60   # det2 at 60 % of time budget
TRAP_DETOUR_RAMP_OUT_FRACTION:  float = 0.80   # ret  at 80 % of time budget

BEZIER_HULL_REDUCTION_FACTOR:   float = 0.90   # 10 % speed reduction per step
BEZIER_HULL_MAX_REDUCTIONS:     int   = 20     # Hard cap on reduction iterations
